### ISSUE TITLE
Bullet Lists - Depth limits

### ISSUE THREAD

**Issue by DamianFlynn** [innofactororg/ghw-markdown-convert#1]
A list which is 5 elements deep results in an error in the Pandoc process

I have a requirement to support lists 6 deep, preferably 7 or 8 if possible
Sample pipeline can be observed: https://github.com/innofactororg/tst-playground-reijoh/runs/8123699461?check_suite_focus=true#step:18:25

This Markdown will trigger the error

```markdown
- Storage Account: `pgovlog`
  - Performance: **Standard**
  - Replication: **Geo-redundant storage (GRS)**
  - Blob Service:
    - Containers: **insights-activity-logs**
      - Access Policy: **Immutable Blob Storage**
        - Set retention period for: **X + 1 days**
        - Allow Protected Append Writes To: **None**
```

will generate the error:

```
Error producing PDF.
! LaTeX Error: Too deeply nested.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.1444         \tightlist

WARNING: Unable to create /home/runner/work/tst-playground-reijoh/tst-playground-reijoh/azGovernance-document.pdf
Error: Process completed with exit code 1.
```

**Comment by ghost** [comment]
Fixed in commits:
<https://github.com/innofactororg/ghw-markdown-convert/commit/1713c67acd123c08e3b8da5948e437eb37090b91>
<https://github.com/innofactororg/ghw-markdown-convert/commit/7751dcc5615160ebd2bd74d9643fbd9dd0a9d99b>
