### ISSUE TITLE
[Bug]: heading level 1 to a new page

### ISSUE THREAD

**Issue by DamianFlynn** [innofactororg/ghw-markdown-convert#12]
### Operating system

Na

### Terraform Version

Na

### Bug description

Heading Level 1 should be rendered to a new page in the output pdf

### Steps to reproduce

Add 2 level 1 headings and they will render on the same output page 

### Relevant log output

```shell
N/a
```

**Comment by ghost** [comment]
This has been solved. See example:

![image](https://user-images.githubusercontent.com/5260092/201431967-73be6f7b-4f81-462f-926e-76dd88507d57.png)

Action that built the pdf:
https://github.com/innofactororg/tst-playground-reijoh/actions/runs/3448015419
