### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by DamianFlynn** [innofactororg/ghw-markdown-convert#15]
### Operating system

GitHub Runner

### Terraform Version

n/a

### Bug description

build fails based on a dependant file missing
! LaTeX Error: File `hardwrap.sty' not found.
! LaTeX Error: File `sectsty.sty' not found.

### Steps to reproduce

Run the pipeline with the action linked to the @main branch

### Relevant log output

```shell
Creating /home/runner/work/acf-gls-docs-azreview/acf-gls-docs-azreview/GLS-NetworkReport.pdf
Error producing PDF.
! LaTeX Error: File `hardwrap.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.53 \RequirePackage{hardwrap}[2011/02/12]
```

after pinning to 0.1.0 and re-running, i get another similar error

```shell
  
Creating /home/runner/work/acf-gls-docs-azreview/acf-gls-docs-azreview/GLS-NetworkReport.pdf
Error producing PDF.
! LaTeX Error: File `sectsty.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.132 \sectionfont
```

**Comment by ghost** [comment]
Incorrect usage, Ensure to call innofactororg/ghw-markdown-convert/.github/workflows/build-documentation.yml@main
