### ISSUE TITLE
bug in formatting of reference links

### ISSUE THREAD

**Issue by DamianFlynn** [innofactororg/ghw-markdown-convert#2]
![image](https://user-images.githubusercontent.com/6288143/187855857-aeff09ef-a498-4d6a-90a9-5e734d9ed953.png)

The referencing links are appended at the end of the table, if the table spans multiple pages, On each of the page the reference are put in the footnote area, except for the last pages of the table

Example: https://github.com/innofactororg/tst-playground-reijoh/actions/runs/2967190536
Page 9

Note that this also repeats on each subsequent page that the table spans

**Comment by ghost** [comment]
I believe this is sorted now:
Example (page 8 and 9): <https://github.com/innofactororg/tst-playground-reijoh/actions/runs/3443972927>
![image](https://user-images.githubusercontent.com/5260092/201305118-ae2aec7e-50e8-4cb7-8e20-85c67052fcbb.png)

PR: https://github.com/innofactororg/ghw-markdown-convert/pull/14
