### ISSUE TITLE
Bug in Table alignment is not consistent

### ISSUE THREAD

**Issue by DamianFlynn** [innofactororg/ghw-markdown-convert#3]
Tables with 2 columns are being centered on the page, These should be left aligned or set to page width

![image](https://user-images.githubusercontent.com/6288143/187862338-114e9a91-ca66-471e-8906-9d2efaabcf3a.png)

However, this is not consistent in the page generation

![image](https://user-images.githubusercontent.com/6288143/187862414-d9c67963-a896-44fd-9fb3-fc1374891308.png)

**Comment by ghost** [comment]
I have mentioned this issue before. When I first noticed it, I tried to find a fix for it, but I could not find one. This has to do with how pandoc treat markdown tables and I will have some more stabs at this to see if I can find a solution, but this is the limitations I have noticed with tables:

* Avoid tables that are smaller than 73 characters, those tables will be centered. Use a bullet list instead if possible.
* Avoid tables that span more than 90 characters, those tables can become compressed and text may be unreadable.

**Comment by AmusingMallard** [comment]
I am guessing this is the same issue. This is from the "deployment requirements" document. Third column is unreadable.
Start of table:
![image](https://user-images.githubusercontent.com/23269655/194892166-e52c2473-2acc-4653-b2f9-a113c3e9b9c6.png)
Continues on next page. Similar on the third page:
![image](https://user-images.githubusercontent.com/23269655/194891989-90b04407-4c50-44b4-91c5-0d406193574c.png)

**Comment by ghost** [comment]
Yes, this is the same issue. Until (if ever) we have a fix, the solution is to not create this information as a table (e.g., use a list for example) or adjust the table content to be within the limits mentioned before.

**Comment by AmusingMallard** [comment]
@DamianFlynn  I believe this is your document?

**Comment by ghost** [comment]
I have looked some more at this. Pandoc generates latex that always center tables, e.g. `\begin{longtable}[]`

We want the `[]` in the above example to become `[l]`.

We could try to run pandoc two times instead of once like today. First time to generate the latex version of the document, then use sed to replace the default table formatting of pandoc, and then convert the latex to pdf.

**Comment by ghost** [comment]
This is now fixed:

After reading the documentation for the longtable package I found a simpler solution to this than using sed etc as hinted above.
![image](https://user-images.githubusercontent.com/5260092/201498381-f475caf6-5f0d-44bf-b387-d62289f8b166.png)

The action that built the pdf above:
<https://github.com/innofactororg/acf-solution-virtual_datacenter/actions/runs/3452920388>
