### ISSUE TITLE
[Bug]: missing default PNG files during build

### ISSUE THREAD

**Issue by DamianFlynn** [innofactororg/ghw-markdown-convert#30]
### Operating system

build container

### Bug description

the following warning is presented, higlighting missing PNG files 

Run $Global:ProgressPreference = 'SilentlyContinue';
  $Global:ProgressPreference = 'SilentlyContinue';
  $forceDefault = 'false' -eq 'true';
  & git config --global safe.directory '*';
  & /usr/local/mdconvert/mdconvert.ps1 -Title 'Innofactor Cloud Framework' -Subtitle 'AVD Pattern High Level Design' -Project '' -Folder 'patterns/blueprints/avd/docs' -Template 'designdoc' -OrderFile 'doc.order' -OutFile 'innofactor-datacenter-avd-high-level-design.pdf' -DefaultAuthor 'Innofactor Azure Cloud Team' -DefaultDescription 'Azure Virtual Desktop Pattern High Level Design' -ForceDefault:$forceDefault
  shell: pwsh -command ". '{0}'"
  
Creating /__w/azure-solutions/azure-solutions/innofactor-datacenter-avd-high-level-design.pdf
**Warning:  Could not fetch resource ./icons/powershell.png: replacing image with description
Warning:  Could not fetch resource ./icons/terraform.png: replacing image with description**

**Comment by ghost** [comment]
Not sure how this is a bug, the files ./icons/powershell.png and ./icons/terraform.png must exist under folder patterns/blueprints/avd/docs, but I don't believe they do.
