### ISSUE TITLE
[Feature]: SVG Support

### ISSUE THREAD

**Issue by DamianFlynn** [innofactororg/ghw-markdown-convert#5]
### Describe the solution you'd like

Currently PNG files, are supported in the compiled output, I would like the tool to also support SVG.

When adding SVG files at the moment the pipe failed with an error of a missing converter tool

### Relevant examples or references

None

### Additional information

none

**Comment by ghost** [comment]
SVG support is now present:
![image](https://user-images.githubusercontent.com/5260092/202441051-f1e8451b-e979-4b25-98e0-500f5c717192.png)

![image](https://user-images.githubusercontent.com/5260092/202441100-d10a67f0-af37-4bb7-9318-f2696b258369.png)
