### ISSUE TITLE
[Feature]: Add support for 'Dendron' markdown features

### ISSUE THREAD

**Issue by DamianFlynn** [innofactororg/ghw-markdown-convert#6]
### Describe the solution you'd like

Dendron uses [[ for wiki links in the pages, these should be added to the generated outpur
Pandoc filters for making Dendron links work properly
a script for adding bibliography information (or other data) to all markdown files in a vault

### Relevant examples or references

This extension has been developed to add the functions to PanDoc

### Additional information

none

**Comment by ghost** [comment]
Not sure why we need this. It's just another way to write a link. Why not make it mandatory to stick with one way to write a link. Adding many options to do one thing is not simplifying, it's rather complicating. Just my thought.
