### ISSUE TITLE
[Feature]: Add Mermaid Diagrams support

### ISSUE THREAD

**Issue by DamianFlynn** [innofactororg/ghw-markdown-convert#7]
### Describe the solution you'd like

We still use mermaid for some of our documents, currently the build process is not processing these

### Relevant examples or references

We should add the [pandoc-mermaid-filter](https://github.com/timofurrer/pandoc-mermaid-filter)

### Additional information

none

**Comment by ghost** [comment]
Pandoc filters are tricky. This one fails with "Error in $: Failed reading: not a valid json value at 'Generatingsinglemermaidchart'". Suggest alternative method like graphviz to generate png:
https://skeltonthatcher.com/2017/10/05/auto-generated-infrastructure-graphs-terraform-plans/
