### ISSUE TITLE
[Feature]: Use a Container for the runner

### ISSUE THREAD

**Issue by DamianFlynn** [innofactororg/ghw-markdown-convert#9]
### Describe the solution you'd like

Currently we are using a default runner, which has to install all the dependencies for every execution, we should have this action converted so that it is implemented using a container to reduce the execution time

### Relevant examples or references

The action is currently a [composite action](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action)

It should be refactored to be a [container action](https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action)

### Additional information

none

**Comment by ghost** [comment]
A container has been created. It is stored at innofactoriac.azurecr.io in repository mdconvert. A sample call workflow has been added at <https://github.com/innofactororg/ghw-markdown-convert/blob/main/.github/workflows/sample-call-convert-markdown.yml>. All parameters showed in the sample call workflow are optional. The Template parameter only support designdoc at the moment (this is the only template we have), but if needed we can add more templates.
